name: CI Gatekeeper

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-quality-checks:
    # Syntax: skybit-agency/{repo}/.github/workflows/{file}@{branch}
    uses: skybit-agency/shared-devops/.github/workflows/nextjs-ci.yml@main
    with:
      node-version: '24' # Optional: Defaults to 20 if omitted
